:bug: Updated NuGet package versions in CommandQuery.AzureFunctions
Bug:
error CS1503: Argument 3: cannot convert from 'Microsoft.Azure.WebJobs.Host.TraceWriter [D:\Program Files (x86)\SiteExtensions\Functions\1.0.11002\bin\Microsoft.Azure.WebJobs.Host.dll]' to 'Microsoft.Azure.WebJobs.Host.TraceWriter [D:\home\data\Functions\packages\nuget\Microsoft.Azure.WebJobs\2.0.0\lib\net45\Microsoft.Azure.WebJobs.Host.dll]'